[project]
name = "target-detector"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "opencv-python",
    "numpy",
    "logging>=0.4.9.6",
    "pytest>=8.4.2",
    "allure-pytest>=2.15.0",
]
